# Generated by Django 3.1.6 on 2021-02-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
