# Generated by Django 3.1.6 on 2021-04-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210206_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
