version: "3"

volumes:
  postgres_data:
  node-modules:
  static_volume:

services:
  django:
    build: ./backend
    command: gunicorn random_quiz.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/random-quiz/backend/static
    expose:
      - 8000
    env_file:
      # 環境変数に設定するファイル
      - ./backend/.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.db

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/random-quiz/frontend/
      # package.json の位置を指定
      - node-modules:/random-quiz/frontend/random-quiz/node_modules
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/random-quiz/backend/static
    ports:
      - 1337:80
    depends_on:
      - django
