version: "3"

volumes:
  postgres_data:
  node-modules:

services:
  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/random-quiz/backend/
    ports:
      - 8000:8000
    env_file:
      # 環境変数に設定するファイル
      - ./backend/.env
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_app
      - POSTGRES_USER=UG
      - POSTGRES_PASSWORD=task_App

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/random-quiz/frontend/
      # package.json の位置を指定
      - node-modules:/random-quiz/frontend/random-quiz/node_modules
    ports:
      - "3000:3000"
